language: node_js
node_js: '10'
notifications:
  slack:
    secure: L2yUSMA8vw6ckAmzlwMtZtOG94xnkVS+85slvd16nfAcgXq67D/HUjs9vr6vahQE7KPkEFFzlIRKQxfZ+uJ1JIHRDem6se0HM0bDM7n55dTowWV31GDm7tpDO61CCMYmcyEJpMaaOWdu3Dsr4JnC7bEmQpmKdjZKWp2ImwUbGvtHv60uWbP7kh0JZOM5VEDwkw+gCr+ngG2R9C83egQNzMknru7B8TJguaF0C0O/b97ccgYs6iUm9tEpsEVYA+45qFTJSmfQi9cYkYTd2KO8VUxsKXX7UJdSSQtheT/PUhzcnfUnN/PCWo7oNy21G/z7uhqRdyCk1m+O4+EBIiqMIBY8203s44xcPeJtMbgf8Ouvazk9JSwwzlthvx1/bpwA+RDwDzaV96+HQ1WUZmjFWRpmuSCep1C4AZ0P7QK6Q4HVnYDGSi8hbS5UVPdxgLsuZ01HTkU1jnn4UtbK6hQjbhaB83iCm1uE2nvAFkarzukvT4hWcH1niGZ5rYJhvD4JvwWnEakYwA/YevrwwKNSkqLAL0lxwYIlVrUv5Rv+IlwLolOwNKiS2UBW9m8VnyBhszUozal6Wl5kWkTWQQKkJwuyc7Omp4qJ56MISpzMeBz0DpqtjXhsvynR5HPMidLL0B9fptiu/v00bs5VUy2wEIV5CZlIlB8M+O2WOk6ZjSA=
script:
  - yarn
  - yarn build
  - yarn deploy:dev
env:
  SERVERLESS_ACCESS_KEY:
    secure: avMbAu9w27WG4JMBWFtPLkr36KSP0xgBC7PWQCjDkIgMHY49Okr8T8pn/5X/n8Pv2Srl+NSR+lXL8lBomg3TCJkyxq8RUPQq9rZNzNEQ6k43JGRzVN+gscTIaHCxpKyLvoD5IE4/jH5x9ZAZvd6gej8kE6Sx/U5PvLfSEHGOHhpFBUXkIedSURj0y51M8zccG0fBUYCD1eFZnlhaozt0oUW/ABMDEtYFLTcHpeDsQXyjU1ZI1lY/mSKz2zY1kCWNvH0WhQCwmK3fzaNVkLnkZ7qTndlV5B0uSd384uEg/Fr+7mLyUIndgJhWPwGRiB7n6DcUs227pUK44ec8ggrig5M4PADyo2oViy1Cu+P7rugf9Je19WKqa3mWbWKOpyO2dEmz/uZuwblWYR6R1v9WKUOnWOZmgGH+KcDjDqgfVcYpRNrMe+B5LsFbt2bwPSAGFWWvqlSiFezBAM1UJMlnqRBPEcDtt8tjjPbtrwbGllNAuCq3mZ6aEOUHDKgeG/CDf4E+EseiFgbSfhzZ/VPr1PBW4qJrwNXrrEyxj+aFNyGnFJgOHyTgA6t5/mUUHP/b6UoJsHBTFke1tyjjQYiKPypcEPAthncOvKUjPCtdGC5KfL5H4jwq7nNauvefXIYlQYCoMb+LqwoNOGCihbHyicBqlgsgBmF2iu2CJz9Appw=
